language: java
jdk:
  oraclejdk8
script:
  -mvn clean install -f monitoring-api/pom.xml
  -mvn clean install -f monitoring/pom.xml
  -mvn clean install -f elasticsearch/pom.xml
notifications:
  email: false
